---
title: WIN Projektgebiete
subtitle: Übersichtskarten über alle Projketgebiete von WIN
output: html_document
out_dir: "docs"
---


```{r, echo = FALSE}
knitr::opts_chunk$set(results="asis", message=FALSE, warning=FALSE)
```


```{r}
library(pander)
library(tidyverse)
library(tmap)

tmap_mode("view")


```



### Übersichtskarte

```{r, fig.width=10, fig.height=10}
load("gemeinden_projekte.Rda")


gemeinden_projekte <- gemeinden_projekte %>% 
  transmute(
    bez = projektperimeter_gemeinde,
    Projekt = projektbezeichnung,
    )


mymap <- tm_shape(gemeinden_sel) + tm_polygons() + tm_shape(gemeinden_projekte, name = "Projekte") + tm_polygons(alpha = 0.5, col = "Projekt",legend.show = FALSE)


tmap::tmap_save(mymap, "docs/index.html")

st_touches(gemeinden_projekte, gemeinden, sparse = FALSE) %>%
  apply(2, any)



gemeinden_sel <- gemeinden[gemeinden_projekte,,op = st_touches]



gemeinden_projekte %>%
  group_by(projektbezeichnung) %>%
  summarise() %>%
  tm_shape() + tm_polygons()

plot(gemeinden_projekte, max.plot = 1)
```

