---
title: "Untitled"
output: 
  html_document: default
---

```{r}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(dplyr)
library(readr)
library(tidyr)
library(sf)
library(stringr)


gemeinden <- st_read("data/gemeinden.gpkg", query = "SELECT name as projektperimeter_gemeinde, kantonsnummer, bezirksnummer, geom FROM gemeinden;")

projekte <- read_csv("data/Projekte_nach_Gemeinde.xlsx - Projekte.csv") %>%
  janitor::clean_names() %>%
  group_by(across()) %>%
  summarise(.groups = "drop")


projekte_meta <- read_csv("data/Projekte_nach_Gemeinde.xlsx - Zusatzinfo.csv") %>%
  janitor::clean_names() %>%
  mutate(
    projektbezeichnung = case_when(
      projektbezeichnung == "Gantrisch"~"Naturpark Gantrisch",
      projektbezeichnung == "Parc du Doubs"~"Parc de Doubs",
      projektbezeichnung == "Réseaux La Frontière"~"Réseaux Frontière",
      TRUE~projektbezeichnung
    )
  )


projekte <- left_join(projekte, projekte_meta, by = "projektbezeichnung")

anti_join(projekte,gemeinden, by = "projektperimeter_gemeinde") %>%
  select(projektbezeichnung, projektperimeter_gemeinde) %>%
  kableExtra::kable() %>% kableExtra::kable_styling()

gemeinden_projekte <- gemeinden %>% 
  left_join(projekte, by = "projektperimeter_gemeinde") %>%
  filter(!is.na(projektbezeichnung)) %>%
  st_zm()


```


Check individual projects

```{r}

gemeinden_projekte_filter <- filter(gemeinden_projekte, projektbezeichnung == "Schaffhausen") %>% st_union()

gemeinden_filter <- gemeinden[st_touches(gemeinden, gemeinden_projekte_filter, sparse = FALSE),]

tm_shape(gemeinden_filter)  + tm_polygons() +
tm_shape(gemeinden_projekte_filter) + tm_borders(col = "red") 
  

```



```{r}
gemeinden_projekte2 <- gemeinden_projekte %>% 
  select(-kantonsnummer, -bezirksnummer, -projektperimeter_gemeinde) %>%
  relocate(projektbezeichnung) %>%
  group_by(across(-matches("geom"))) %>%
  summarise(.groups = "drop")


gemeinden_projekte2$mycols <- colorRampPalette(RColorBrewer::brewer.pal(12, "Set3"))(nrow(gemeinden_projekte2))



mymap <- gemeinden_projekte2 %>%
  split(.$projektbezeichnung) %>%
  purrr::imap(function(x,y){
    col <- unique(x$mycols)
    tm_shape(x,name = y, bbox = st_bbox(gemeinden_projekte2)) + tm_polygons(col = col,alpha = 0.8) + tm_text(text = "projektbezeichnung")
  }) %>%
  purrr::reduce(function(x, y){x+y})

mymap

# mymap <- tm_shape(gemeinden_projekte2, name = "Projekte") + 
#   tm_polygons(alpha = 0.5, col = "projektbezeichnung",legend.show = TRUE,popup.vars = c("projektbezeichnung", "stand", "laufzeit", "projektleiter", "traegerschaft"))

tmap::tmap_save(mymap, "docs/index.html", title = "Projekte WIN Wieselnetz")
```


```{r}
# render_report <- function(projektbezeichnung) {
# 
#   out_file <- file.path("docs",paste0(make.names(projektbezeichnung),".html"))
# 
#   parameters <- list(projektbezeichnung = projektbezeichnung)
# 
#   rmarkdown::render("param.Rmd", output_file = out_file, params = parameters)
#   invisible(TRUE)
# }
# 
# map(unique(gemeinden_projekte$projektbezeichnung), ~render_report(.x))
# 
# rmarkdown::render("index.Rmd",output_file = "docs/index.html")

```


